<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
    <line>
      <![CDATA[<a href="\testng-maven\target\surefire-reports\failure_screenshots\validate_empty_field_login_failure_07_12_2020_11_52_43.png"target="_blank"> screenshot]]>
    </line>
  </reporter-output>
  <suite name="tests.LoginTest" duration-ms="11043" started-at="2020-12-07T11:52:33 IST" finished-at="2020-12-07T11:52:44 IST">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="11043" started-at="2020-12-07T11:52:33 IST" finished-at="2020-12-07T11:52:44 IST">
      <class name="tests.LoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.LoginTest@3d86dfbb]" name="setUp" is-config="true" duration-ms="6878" started-at="2020-12-07T11:52:33 IST" finished-at="2020-12-07T11:52:40 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="validate_valid_user_login()[pri:0, instance:tests.LoginTest@3d86dfbb]" name="validate_valid_user_login" duration-ms="1436" started-at="2020-12-07T11:52:40 IST" finished-at="2020-12-07T11:52:41 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_valid_user_login -->
        <test-method status="PASS" signature="validate_locked_out_user_login_failure()[pri:1, instance:tests.LoginTest@3d86dfbb]" name="validate_locked_out_user_login_failure" duration-ms="481" started-at="2020-12-07T11:52:41 IST" finished-at="2020-12-07T11:52:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_locked_out_user_login_failure -->
        <test-method status="PASS" signature="validate_invalid_password_login_failure()[pri:2, instance:tests.LoginTest@3d86dfbb]" name="validate_invalid_password_login_failure" duration-ms="456" started-at="2020-12-07T11:52:42 IST" finished-at="2020-12-07T11:52:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_invalid_password_login_failure -->
        <test-method status="FAIL" signature="validate_empty_field_login_failure()[pri:3, instance:tests.LoginTest@3d86dfbb]" name="validate_empty_field_login_failure" duration-ms="112" started-at="2020-12-07T11:52:42 IST" finished-at="2020-12-07T11:52:43 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at pages.LoginPage.hasEmptyFieldsError(LoginPage.java:61)
at tests.LoginTest.validate_empty_field_login_failure(LoginTest.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner$$Lambda$71/0000000000000000.accept(Unknown Source)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href="\testng-maven\target\surefire-reports\failure_screenshots\validate_empty_field_login_failure_07_12_2020_11_52_43.png"target="_blank"> screenshot]]>
            </line>
          </reporter-output>
        </test-method> <!-- validate_empty_field_login_failure -->
        <test-method status="PASS" signature="validate_broken_images_for_problem_user()[pri:4, instance:tests.LoginTest@3d86dfbb]" name="validate_broken_images_for_problem_user" duration-ms="555" started-at="2020-12-07T11:52:43 IST" finished-at="2020-12-07T11:52:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_broken_images_for_problem_user -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:tests.LoginTest@3d86dfbb]" name="tearDown" is-config="true" duration-ms="647" started-at="2020-12-07T11:52:43 IST" finished-at="2020-12-07T11:52:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.LoginTest -->
    </test> <!-- Command line test -->
  </suite> <!-- tests.LoginTest -->
</testng-results>
